Languages = {
    ["en-us"] = {
        Name = "American English",
        CommonTongue = "US English"
    },

    ["pt-br"] = {
        Name = "Português Brasileiro",
        CommonTongue = "Brazilian Portuguese"
    },

    ["ar-001"] = {
        Name = "العربية",
        CommonTongue = "Arabic"
    },

    ["ja-jp"] = {
        Name = "日本語",
        CommonTongue = "Japanese"
    },

    ["es-es"] = {
        Name = "Español - España",
        CommonTongue = "Spanish - Spain"
    },

    ["ru-ru"] = {
        Name = "русский",
        CommonTongue = "Russian"
    },

    ["zh-cn"] = {
        Name = "中文(简体",
        CommonTongue = "Simplified Chinese"
    },

    ["fr-fr"] = {
        Name = "Français - France",
        CommonTongue = "French"
    },

    ["de-de"] = {
        Name = "Deutsch",
        CommonTongue = "German"
    }

}

return Languages