Languages = {
    ["American English"] = {
        Name = "US English",
        CodeID = "en-us",
    },

    ["British English"] = {
        Name = "British English",
        CodeID = "en-gb",
    },

    ["Português Brasileiro"] = {
        Name = "Brazilian Portuguese",
        CodeID = "pt-br",
    },

    ["Português de Portugal"] = {
        Name = "Portuguese Portuguese",
        CodeID = "pt-pt",
    },

    ["العربية"] = {
        Name = "Arabic",
        CodeID = "ar-001",
    },

    ["Español - España"] = {
        Name = "Spanish - Spain",
        CodeID = "es-es",
    },

    ["Español - México"] = {
        Name = "Spanish - Mexico",
        CodeID = "es-mx",
    },

    ["日本語"] = {
        Name = "Japanese",
        CodeID = "ja=jp",
    },

    ["русский"] = {
        Name = "Russian",
        CodeID = "ru-ru",
    },

    ["中文(简体)"] = {
        Name = "Chinese (Simplified)",
        CodeID = "zh-cn",
    },

    ["中文(繁體)"] = {
        Name = "Chinese (Traditional)",
        CodeID = "zh-tw",
    },

    ["Français - France"] = {
        Name = "French - France",
        CodeID = "fr-fr",
    },

    ["Français - Canada"] = {
        Name = "French - Canada",
        CodeID = "fr-ca",
    },

    ["Deutsch"] = {
        Name = "German",
        CodeID = "de-de",
    },
}

return Languages