local Answering = {}

Answering.Answering = {
	["Question"] = {
		"what",
		"can",
		"how",
		"will",
		"would",
		"should",
		"do",
		"could",
	},
	["Subject"] = {
		"you",
		"i",
		"it",
		"we",
	},
	["Verb"] = {
		"be",
		"help",
		"order",
		"pay",
		"want",
		"sell",
		"take",
		"work",
		"suggest",
		"get",
		"have",
		"know",
		"like",
		"look",
		"tell",
		"need",
		"leave",
	},
	["Extra"] = {
		"anything",
		"no",
		"yes",
		"for",
		"of",
		"to",
		"out",
	},
	["Object"] = {
		"money",
		"today",
		"options",
		"pizzas",
		"tacos",
		"time",
		"pastels",
	},
}

return Answering
