DialogueWords = {}

DialogueWords.EnglishWords = {

	{
		word = "what",
	},
	{
		word = "can",
	},
	{
		word = "how",
	},
	{
		word = "will",
	},
	{
		word = "would",
	},
	{
		word = "should",
	},
	{
		word = "do",
		options = {
			"does",
			"did",
			"done",
			"doing"
		}
	},
	{
		word = "could",
	},
	{
		word = "you",
		options = {
			"your",
			"yours",
			"thou",
			"thee",
			"thy",
			"thine",
		},
	},
	{
		word = "i",
		options = {
			"me",
			"mine",
			"my",
		},
	},
	{
		word = "it",
		options = {
			"its",
		},
	},
	{
		word = "we",
		options = {
			"us",
			"our",
			"ours",
		},
	},
	{
		word = "be",
		options = {
			"am",
			"are",
			"is",
			"was",
			"were",
		},
	},
	{
		word = "help",
		options = {
			"helps",
			"helped",
			"helping",
		},
	},
	{
		word = "order",
		options = {
			"orders",
			"ordered",
			"ordering",
		},
	},
	{
		word = "pay",
		options = {
			"pays",
			"paid",
			"paying",
		},
	},
	{
		word = "want",
		options = {
			"wants",
			"wanted",
			"wanting",
		},
	},
	{
		word = "sell",
		options = {
			"sells",
			"sold",
			"selling",
		},
	},
	{
		word = "take",
		options = {
			"takes",
			"took",
			"taken",
			"taking",
		},
	},
	{
		word = "work",
		options = {
			"works",
			"worked",
			"working",
		},
	},
	{
		word = "suggest",
		options = {
			"suggests",
			"suggested",
			"suggesting",
			"suggestion",
			"suggestions"
		}
	},
	{
		word = "get",
		options = {
			"gets",
			"got",
			"gotten",
			"getting"
		}
	},
	{
		word = "have",
		options = {
			"has",
			"had",
			"having"
		}
	},
	{
		word = "know",
		options = {
			"knows",
			"knew",
			"known",
			"knowing"
		}
	},
	{
		word = "like",
		options = {
			"likes",
			"liked",
			"liking"
		}
	},
	{
		word = "look",
		options = {
			"looks",
			"looked",
			"looking"
		}
	},
	{
		word = "tell",
		options = {
			"tells",
			"told",
			"telling"
		}
	},
	{
		word = "need",
		options = {
			"needs",
			"needed",
			"needing"
		}
	},
	{
		word = "leave",
		options = {
			"leaves",
			"left",
			"leaving"
		}
	},
	{
		word = "anything"
	},
	{
		word = "no",
		options = {
			"not"
		}
	},
	{
		word = "yes"
	},
	{
		word = "for"
	},
	{
		word = "of"
	},
	{
		word = "to"
	},
	{
		word = "out"
	},
	{
		word = "money"
	},
	{
		word = "today"
	},
	{
		word = "option",
		options = {
			"options"
		}
	},
	{
		word = "pizza",
		options = {
			"pizzas"
		}
	},
	{
		word = "taco",
		options = {
			"tacos"
		}
	},
	{
		word = "pastel",
		options = {
			"pastels"
		}
	},
	{
		word = "time",
		options = {
			"times",
			"timed",
			"timing"
		}
	},
}

return DialogueWords