DialogueWords = {

	{
		word = "what",
		combinedOptions = {
			"what's",
			"what'd",
			"what'll",
			"what've",
		},
	},
	{
		word = "can",
		combinedOptions = {
			"cannot",
			"can't",
		},
	},
	{
		word = "how",
		combinedOptions = {
			"how's",
			"how'd",
			"how'll",
			"how've",
		},
	},
	{
		word = "will",
		combinedOptions = {
			"i'll",
			"you'll",
			"he'll",
			"she'll",
			"it'll",
			"we'll",
			"what'll",
			"how'll",
			"won't",
		},
	},
	{
		word = "would",
		combinedOptions = {
			"i'd",
			"you'd",
			"he'd",
			"she'd",
			"it'd",
			"we'd",
			"what'd",
			"how'd",
			"wouldn't",
			"would've",
		},
	},
	{
		word = "should",
		combinedOptions = {
			"shouldn't",
			"should've",
		},
	},
	{
		word = "do",
		options = {
			"does",
			"did",
			"done",
			"doing",
		},
		combinedOptions = {
			"don't",
			"doesn't",
			"didn't",
			"donno",
			"ain't",
		},
	},
	{
		word = "could",
		combinedOptions = {
			"couldn't",
			"could've",
		},
	},
	{
		word = "you",
		options = {
			"your",
			"yours",
			"thou",
			"thee",
			"thy",
			"thine",
		},
		combinedOptions = {
			"you're",
			"you'd",
			"you'll",
			"you've",
		},
	},
	{
		word = "i",
		options = {
			"me",
			"mine",
			"my",
		},
		combinedOptions = {
			"i'm",
			"i'll",
			"i'd",
			"i've",
		},
	},
	{
		word = "it",
		options = {
			"its",
		},
		combinedOptions = {
			"it's",
			"it'd",
			"it'll",
			"it've",
		},
	},
	{
		word = "we",
		options = {
			"us",
			"our",
			"ours",
		},
		combinedOptions = {
			"we're",
			"we'd",
			"we'll",
		},
	},
	{
		word = "be",
		options = {
			"am",
			"are",
			"is",
			"was",
			"were",
		},
		combinedOptions = {
			"i'm",
			"you're",
			"he's",
			"she's",
			"it's",
			"we're",
			"what's",
			"how's",
			"ain't",
			"isn't",
			"aren't",
			"wasn't",
			"weren't",
		},
	},
	{
		word = "help",
		options = {
			"helps",
			"helped",
			"helping",
		},
	},
	{
		word = "order",
		options = {
			"orders",
			"ordered",
			"ordering",
		},
	},
	{
		word = "pay",
		options = {
			"pays",
			"paid",
			"paying",
		},
	},
	{
		word = "want",
		options = {
			"wants",
			"wanted",
			"wanting",
		},
		combinedOptions = {
			"wanna",
		},
	},
	{
		word = "sell",
		options = {
			"sells",
			"sold",
			"selling",
		},
	},
	{
		word = "take",
		options = {
			"takes",
			"took",
			"taken",
			"taking",
		},
	},
	{
		word = "work",
		options = {
			"works",
			"worked",
			"working",
		},
	},
	{
		word = "suggest",
		options = {
			"suggests",
			"suggested",
			"suggesting",
			"suggestion",
			"suggestions",
		},
	},
	{
		word = "get",
		options = {
			"gets",
			"got",
			"gotten",
			"getting",
		},
		combinedOptions = {
			"gotta",
		},
	},
	{
		word = "have",
		options = {
			"has",
			"had",
			"having",
		},
		combinedOptions = {
			"haven't",
			"hasn't",
			"i've",
			"you've",
			"ain't",
		},
	},
	{
		word = "know",
		options = {
			"knows",
			"knew",
			"known",
			"knowing",
		},
	},
	{
		word = "like",
		options = {
			"likes",
			"liked",
			"liking",
		},
	},
	{
		word = "look",
		options = {
			"looks",
			"looked",
			"looking",
		},
	},
	{
		word = "tell",
		options = {
			"tells",
			"told",
			"telling",
		},
	},
	{
		word = "need",
		options = {
			"needs",
			"needed",
			"needing",
		},
	},
	{
		word = "leave",
		options = {
			"leaves",
			"left",
			"leaving",
		},
	},
	{
		word = "anything",
	},
	{
		word = "no",
		options = {
			"not",
			"nope",
			"ain't",
			"isn't",
			"aren't",
			"wasn't",
			"weren't",
			"wouldn't",
			"couldn't",
			"shouldn't",
			"won't",
		},
	},
	{
		word = "yes",
		options = {
			"yeah",
			"yup",
		},
	},
	{
		word = "for",
	},
	{
		word = "of",
		combinedOptions = {
			"outta",
		},
	},
	{
		word = "to",
		combinedOptions = {
			"gotta",
			"wanna",
		},
	},
	{
		word = "out",
		combinedOptions = {
			"outta",
		},
	},
	{
		word = "money",
	},
	{
		word = "today",
	},
	{
		word = "option",
		options = {
			"options",
		},
	},
	{
		word = "pizza",
		options = {
			"pizzas",
		},
	},
	{
		word = "taco",
		options = {
			"tacos",
		},
	},
	{
		word = "pastel",
		options = {
			"pastels",
		},
	},
	{
		word = "time",
		options = {
			"times",
			"timed",
			"timing",
		},
	},
}

return DialogueWords
